[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
    Sensirion/Sensirion I2C SCD4x@^1.1.0
    crankyoldgit/IRremoteESP8266@^2.8.6
